// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaA1EYAlqoylaDRaaw3YU0lSuxYO7jRQk',
    appId: '1:1013199009204:web:b3a97e0a93390df684aee1',
    messagingSenderId: '1013199009204',
    projectId: 'delivery-app-f0e5b',
    authDomain: 'delivery-app-f0e5b.firebaseapp.com',
    storageBucket: 'delivery-app-f0e5b.appspot.com',
    measurementId: 'G-GC3HGV9HFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-ZbU-g87eREfiQuwRyGQ-UPnVLLLZOQ4',
    appId: '1:1013199009204:android:3cb208100a69463984aee1',
    messagingSenderId: '1013199009204',
    projectId: 'delivery-app-f0e5b',
    storageBucket: 'delivery-app-f0e5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC38rTZuNcqWW5sepSghL2blxPQf0nnfOg',
    appId: '1:1013199009204:ios:c175405e690fd60084aee1',
    messagingSenderId: '1013199009204',
    projectId: 'delivery-app-f0e5b',
    storageBucket: 'delivery-app-f0e5b.appspot.com',
    iosClientId: '1013199009204-i41rjj2rjac67dtv4jtkjltnn9bgt8pn.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryApp',
  );
}
